// Embeds CHIPS.DAT as base64 into js/levels-data.js so the game runs from file:// too.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const datPath = process.argv[2] ?? fileURLToPath(new URL('../original/CHIPS.DAT', import.meta.url));
const outPath = fileURLToPath(new URL('../js/levels-data.js', import.meta.url));

const b64 = readFileSync(datPath).toString('base64');
writeFileSync(outPath,
  `/* Auto-generated by tools/embed.mjs — base64 of the level .DAT file. */\n` +
  `const CHIPS_DAT_BASE64 = "${b64}";\n`);
console.log(`Wrote ${outPath} (${(b64.length / 1024).toFixed(0)} KB base64)`);
